# Rollout Manager Configuration
# All parameters are required and must be provided via command line, this config file, or REST API

# Mooncake transfer device name (e.g., mlx5_0 for InfiniBand)
mooncake_transfer_device_name = ""

# Mooncake transfer protocol (e.g., rdma, tcp)
mooncake_transfer_protocol = "tcp"

allowed_sender_ips = "192.168.0.0/16"
weight_sender_rpyc_base_port = 18861
# Weight sender RPyC endpoints
# These will be automatically populated by the training script
# but can be manually configured here
weight_sender_rpyc_endpoints = []

# Number of mooncake groups per sender
num_mooncake_groups_per_sender = 4
num_mooncake_engines_per_group = 8

max_assigned_batches_per_stats_check = 2
